#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Employee Activity Monitoring System                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 ИНСТРУКЦИЯ ПО ЗАПУСКУ:"
echo ""
echo "Этот проект требует Docker и docker-compose для запуска."
echo "Replit не поддерживает Docker, поэтому запуск возможен только локально."
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🖥️  ЛОКАЛЬНЫЙ ЗАПУСК (на вашем компьютере):"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Клонировать репозиторий:"
echo "   git clone https://github.com/ctolnik/Office-Monitor.git"
echo "   cd Office-Monitor"
echo ""
echo "2️⃣  Запустить инфраструктуру (ClickHouse + MinIO):"
echo "   docker-compose up -d"
echo ""
echo "3️⃣  Проверить что все запустилось:"
echo "   docker-compose ps"
echo ""
echo "4️⃣  Открыть в браузере:"
echo "   Frontend: http://localhost:80"
echo "   Server API: http://localhost:8081"
echo "   MinIO Console: http://localhost:9101"
echo ""
echo "5️⃣  Остановить:"
echo "   docker-compose down"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🪟 WINDOWS АГЕНТ (на рабочих станциях):"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Скачать готовый агент:"
echo "   Скачайте employee-agent.exe из репозитория"
echo ""
echo "2️⃣  Создать конфиг agent/config.yaml:"
echo "   server:"
echo "     url: \"http://ВАШ_IP:8081\""
echo "   agent:"
echo "     computer_name: \"PC001\""
echo ""
echo "3️⃣  Запустить агент:"
echo "   employee-agent.exe -config config.yaml"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📊 НОВЫЕ ФУНКЦИИ (Activity Tracking):"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Отслеживание времени активности (active/idle/offline)"
echo "✅ Извлечение URL из браузеров"
echo "✅ Process catalog для удобных названий программ"
echo "✅ API endpoints:"
echo "   - GET /api/activity/summary - дневной отчет"
echo "   - GET /api/activity/segments - сегменты активности"
echo "   - CRUD /api/process-catalog - справочник программ"
echo ""
echo "📄 Frontend спецификация:"
echo "   См. FRONTEND_TASK_ACTIVITY_TRACKING.md"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "⚠️  ВАЖНО:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "- Проект использует ClickHouse (база данных) и MinIO (хранилище)"
echo "- Требуется Docker и docker-compose"
echo "- В Replit проект НЕ запустится - только локально"
echo "- Агент собран и готов: agent/employee-agent.exe (9.7MB)"
echo "- Все изменения сохранены в GitHub"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📚 Документация:"
echo "   - README_NEW.md - полная документация"
echo "   - QUICKSTART.md - быстрый старт"
echo "   - DEPLOYMENT.md - развертывание"
echo "   - LEGAL_COMPLIANCE.md - юридические аспекты"
echo ""
echo "🔗 GitHub: https://github.com/ctolnik/Office-Monitor"
echo ""
