apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: monitoring
      port: 9000
      server: clickhouse
      username: monitor_user
      tlsSkipVerify: true
    secureJsonData:
      password: $__env{CLICKHOUSE_PASSWORD}
